using Aura.Dashboard.Domain;using Aura.Dashboard.Repositories;using Aura.Dashboard.Services;using Moq;
using Microsoft.Extensions.Configuration;
using Xunit;
namespace Aura.Dashboard.Tests;

public sealed class ServiceTests
{
 [Fact]public void Dashboard_users_have_a_dedicated_collection(){Assert.Equal("staffuser",MongoCollectionNames.StaffUsers);}
 static StaffActor Actor()=>new("a","Alex","a@a.test",Roles.Administrator,"trace");static ManagedMedia Media()=>new(){Id="m",OwnerId="u",OwnerName="Uma",Title="Clip",MediaType="video",ObjectKey="clip"};static StaffUser User()=>new(){Id="u",Name="Uma",Email="u@a.test",PasswordHash="hash",EmailVerified=true};
 [Fact]public async Task Reject_requires_reason(){var sut=new ModerationService(Mock.Of<IMediaRepository>(),Mock.Of<IAuditRepository>());await Assert.ThrowsAsync<DashboardRuleException>(()=>sut.DecideAsync("m",false," ",Actor()));}
 [Fact]public async Task Decision_is_atomic_and_audited(){var mr=new Mock<IMediaRepository>();mr.Setup(x=>x.FindAsync("m")).ReturnsAsync(Media());mr.Setup(x=>x.TrySetReviewStatusAsync("m",ReviewStates.InReview,ReviewStates.Approved)).ReturnsAsync(true);var ar=new Mock<IAuditRepository>();await new ModerationService(mr.Object,ar.Object).DecideAsync("m",true,"fine",Actor());ar.Verify(x=>x.AppendAsync(It.Is<AuditEvent>(e=>e.EventType=="MediaApproved"&&e.Reason=="fine")));}
 [Fact]public async Task Concurrent_decision_is_rejected(){var mr=new Mock<IMediaRepository>();mr.Setup(x=>x.FindAsync("m")).ReturnsAsync(Media());mr.Setup(x=>x.TrySetReviewStatusAsync(It.IsAny<string>(),It.IsAny<string>(),It.IsAny<string>())).ReturnsAsync(false);await Assert.ThrowsAsync<ConcurrencyException>(()=>new ModerationService(mr.Object,Mock.Of<IAuditRepository>()).DecideAsync("m",true,null,Actor()));}
 [Fact]public async Task Administrator_target_is_protected(){var ur=new Mock<IUserRepository>();var u=User();u.IsAdministrator=true;ur.Setup(x=>x.FindAsync("u")).ReturnsAsync(u);var sut=UserService(ur.Object,Mock.Of<IAuditRepository>(),Mock.Of<IResetDelivery>());await Assert.ThrowsAsync<DashboardRuleException>(()=>sut.SetBlockedAsync("u",true,"risk",Actor()));ur.Verify(x=>x.SaveAsync(It.IsAny<StaffUser>()),Times.Never);}
 [Fact]public async Task Blocking_invalidates_sessions_and_audits(){var ur=new Mock<IUserRepository>();var u=User();ur.Setup(x=>x.FindAsync("u")).ReturnsAsync(u);var ar=new Mock<IAuditRepository>();await UserService(ur.Object,ar.Object,Mock.Of<IResetDelivery>()).SetBlockedAsync("u",true,"risk",Actor());Assert.True(u.IsBlocked);Assert.Equal(1,u.SessionVersion);ar.Verify(x=>x.AppendAsync(It.Is<AuditEvent>(e=>e.EventType=="UserBlocked"&&e.Reason=="risk")));}
 [Fact]public async Task Reviewer_must_be_verified_and_active(){var ur=new Mock<IUserRepository>();var u=User();u.EmailVerified=false;ur.Setup(x=>x.FindAsync("u")).ReturnsAsync(u);await Assert.ThrowsAsync<DashboardRuleException>(()=>UserService(ur.Object,Mock.Of<IAuditRepository>(),Mock.Of<IResetDelivery>()).SetReviewerAsync("u",true,Actor()));}
 [Fact]public async Task Reset_delivers_without_recording_token(){var ur=new Mock<IUserRepository>();ur.Setup(x=>x.FindAsync("u")).ReturnsAsync(User());var delivery=new Mock<IResetDelivery>();var audit=new Mock<IAuditRepository>();await UserService(ur.Object,audit.Object,delivery.Object).RequestResetAsync("u",Actor());delivery.Verify(x=>x.SendAsync(It.IsAny<StaffUser>(),It.IsAny<string>(),It.IsAny<DateTime>()));audit.Verify(x=>x.AppendAsync(It.Is<AuditEvent>(e=>e.EventType=="PasswordResetRequested"&&e.Reason==null)));}
 [Fact]public async Task Admin_can_invite_a_reviewer_without_choosing_their_password(){var users=new Mock<IUserRepository>();var invitations=new Mock<IStaffInvitationDelivery>();var tokens=new Mock<ISecureTokenService>();tokens.Setup(x=>x.Create()).Returns("secret-token");tokens.Setup(x=>x.Hash("secret-token")).Returns("safe-hash");var service=new UserManagementService(users.Object,Mock.Of<IAuditRepository>(),Mock.Of<IResetDelivery>(),invitations.Object,tokens.Object);var result=await service.InviteAsync(new(){Name="Rita Reviewer",Email="RITA@EXAMPLE.COM",Role=Roles.Reviewer},Actor());Assert.Equal(string.Empty,result.PasswordHash);Assert.Equal("safe-hash",result.InvitationTokenHash);Assert.False(result.EmailVerified);invitations.Verify(x=>x.SendAsync(result,"secret-token",It.IsAny<DateTime>()));}
 [Fact]public async Task Media_delete_removes_storage_first(){var mr=new Mock<IMediaRepository>();mr.Setup(x=>x.FindAsync("m")).ReturnsAsync(Media());var storage=new Mock<IAssetStorage>();await new MediaManagementService(mr.Object,storage.Object,Mock.Of<IAuditRepository>()).DeleteAsync("m","policy",Actor());storage.Verify(x=>x.DeleteAsync("clip"));mr.Verify(x=>x.DeleteAsync("m"));}
 [Fact]public async Task Media_delete_requires_reason(){await Assert.ThrowsAsync<DashboardRuleException>(()=>new MediaManagementService(Mock.Of<IMediaRepository>(),Mock.Of<IAssetStorage>(),Mock.Of<IAuditRepository>()).DeleteAsync("m","",Actor()));}
 [Fact]public async Task Reporting_maps_all_totals(){var m=new Mock<IMediaRepository>();m.Setup(x=>x.CountsAsync()).ReturnsAsync(new Dictionary<string,long>{{"video",2},{"image",3},{ReviewStates.InReview,1}});var u=new Mock<IUserRepository>();u.Setup(x=>x.CountsAsync()).ReturnsAsync(new Dictionary<string,long>{{"Total",7},{"Verified",5}});var result=await new ReportingService(m.Object,u.Object).GetAsync();Assert.Equal(5,result.TotalMedia);Assert.Equal(7,result.TotalUsers);Assert.Equal(1,result.Pending);}
 [Fact]public async Task First_administrator_requires_configured_token(){var users=new Mock<IUserRepository>();var service=new StaffBootstrapService(users.Object,Mock.Of<IAuditRepository>(),Configuration());Assert.False(await service.IsAvailableAsync());}
 [Fact]public async Task First_administrator_is_created_in_staff_repository_and_audited(){var users=new Mock<IUserRepository>();users.Setup(x=>x.TryAcquireFirstAdministratorBootstrapAsync()).ReturnsAsync(true);var audit=new Mock<IAuditRepository>();var service=new StaffBootstrapService(users.Object,audit.Object,Configuration(("Bootstrap:Token","one-time-token")));var request=new FirstAdministratorRequest{Name="Ada Admin",Email="ADA@EXAMPLE.COM",Password="Strong!Password1",ConfirmPassword="Strong!Password1",SetupToken="one-time-token"};var result=await service.CreateFirstAdministratorAsync(request,"trace-1");Assert.True(result.IsAdmin);Assert.Equal("ada@example.com",result.Email);Assert.True(BCrypt.Net.BCrypt.Verify(request.Password,result.PasswordHash));users.Verify(x=>x.SaveAsync(result));audit.Verify(x=>x.AppendAsync(It.Is<AuditEvent>(e=>e.EventType=="FirstAdministratorCreated"&&e.Reason==null&&e.CorrelationId=="trace-1")));}
 [Fact]public async Task First_administrator_rejects_invalid_token_without_locking(){var users=new Mock<IUserRepository>();var service=new StaffBootstrapService(users.Object,Mock.Of<IAuditRepository>(),Configuration(("Bootstrap:Token","right-token")));var request=new FirstAdministratorRequest{Name="Ada",Email="ada@example.com",Password="Strong!Password1",ConfirmPassword="Strong!Password1",SetupToken="wrong-token"};await Assert.ThrowsAsync<DashboardRuleException>(()=>service.CreateFirstAdministratorAsync(request,"trace"));users.Verify(x=>x.TryAcquireFirstAdministratorBootstrapAsync(),Times.Never);}
 [Fact]public async Task Failed_first_administrator_creation_releases_bootstrap_lock(){var users=new Mock<IUserRepository>();users.Setup(x=>x.TryAcquireFirstAdministratorBootstrapAsync()).ReturnsAsync(true);users.Setup(x=>x.FindByEmailAsync("ada@example.com")).ReturnsAsync(User());var service=new StaffBootstrapService(users.Object,Mock.Of<IAuditRepository>(),Configuration(("Bootstrap:Token","token")));var request=new FirstAdministratorRequest{Name="Ada",Email="ada@example.com",Password="Strong!Password1",ConfirmPassword="Strong!Password1",SetupToken="token"};await Assert.ThrowsAsync<DashboardRuleException>(()=>service.CreateFirstAdministratorAsync(request,"trace"));users.Verify(x=>x.ReleaseFirstAdministratorBootstrapAsync());}

 static UserManagementService UserService(IUserRepository users,IAuditRepository audit,IResetDelivery reset)
 {
  var tokens=new Mock<ISecureTokenService>();tokens.Setup(x=>x.Create()).Returns("token");tokens.Setup(x=>x.Hash(It.IsAny<string>())).Returns("hash");
  return new(users,audit,reset,Mock.Of<IStaffInvitationDelivery>(),tokens.Object);
 }
 static IConfiguration Configuration(params (string Key,string Value)[] values)=>new ConfigurationBuilder().AddInMemoryCollection(values.ToDictionary(x=>x.Key,x=>(string?)x.Value)).Build();
}
