using Aura.Dashboard.Domain;using Aura.Dashboard.Repositories;using Aura.Dashboard.Services;using Moq;
namespace Aura.Dashboard.Tests;
public sealed class ServiceTests
{
 [Fact]public void Dashboard_users_have_a_dedicated_collection(){Assert.Equal("staffuser",MongoContext.CollectionNames.StaffUsers);}
 static StaffActor Actor()=>new("a","Alex","a@a.test",Roles.Administrator,"trace");static ManagedMedia Media()=>new(){Id="m",OwnerId="u",OwnerName="Uma",Title="Clip",MediaType="video",ObjectKey="clip"};static StaffUser User()=>new(){Id="u",Name="Uma",Email="u@a.test",PasswordHash="hash",EmailVerified=true};
 [Fact]public async Task Reject_requires_reason(){var sut=new ModerationService(Mock.Of<IMediaRepository>(),Mock.Of<IAuditRepository>());await Assert.ThrowsAsync<DashboardRuleException>(()=>sut.DecideAsync("m",false," ",Actor()));}
 [Fact]public async Task Decision_is_atomic_and_audited(){var mr=new Mock<IMediaRepository>();mr.Setup(x=>x.FindAsync("m")).ReturnsAsync(Media());mr.Setup(x=>x.TrySetReviewStatusAsync("m",ReviewStates.InReview,ReviewStates.Approved)).ReturnsAsync(true);var ar=new Mock<IAuditRepository>();await new ModerationService(mr.Object,ar.Object).DecideAsync("m",true,"fine",Actor());ar.Verify(x=>x.AppendAsync(It.Is<AuditEvent>(e=>e.EventType=="MediaApproved"&&e.Reason=="fine")));}
 [Fact]public async Task Concurrent_decision_is_rejected(){var mr=new Mock<IMediaRepository>();mr.Setup(x=>x.FindAsync("m")).ReturnsAsync(Media());mr.Setup(x=>x.TrySetReviewStatusAsync(It.IsAny<string>(),It.IsAny<string>(),It.IsAny<string>())).ReturnsAsync(false);await Assert.ThrowsAsync<ConcurrencyException>(()=>new ModerationService(mr.Object,Mock.Of<IAuditRepository>()).DecideAsync("m",true,null,Actor()));}
 [Fact]public async Task Administrator_target_is_protected(){var ur=new Mock<IUserRepository>();var u=User();u.IsAdministrator=true;ur.Setup(x=>x.FindAsync("u")).ReturnsAsync(u);var sut=new UserManagementService(ur.Object,Mock.Of<IAuditRepository>(),Mock.Of<IResetDelivery>());await Assert.ThrowsAsync<DashboardRuleException>(()=>sut.SetBlockedAsync("u",true,"risk",Actor()));ur.Verify(x=>x.SaveAsync(It.IsAny<StaffUser>()),Times.Never);}
 [Fact]public async Task Blocking_invalidates_sessions_and_audits(){var ur=new Mock<IUserRepository>();var u=User();ur.Setup(x=>x.FindAsync("u")).ReturnsAsync(u);var ar=new Mock<IAuditRepository>();await new UserManagementService(ur.Object,ar.Object,Mock.Of<IResetDelivery>()).SetBlockedAsync("u",true,"risk",Actor());Assert.True(u.IsBlocked);Assert.Equal(1,u.SessionVersion);ar.Verify(x=>x.AppendAsync(It.Is<AuditEvent>(e=>e.EventType=="UserBlocked"&&e.Reason=="risk")));}
 [Fact]public async Task Reviewer_must_be_verified_and_active(){var ur=new Mock<IUserRepository>();var u=User();u.EmailVerified=false;ur.Setup(x=>x.FindAsync("u")).ReturnsAsync(u);await Assert.ThrowsAsync<DashboardRuleException>(()=>new UserManagementService(ur.Object,Mock.Of<IAuditRepository>(),Mock.Of<IResetDelivery>()).SetReviewerAsync("u",true,Actor()));}
 [Fact]public async Task Reset_delivers_without_recording_token(){var ur=new Mock<IUserRepository>();ur.Setup(x=>x.FindAsync("u")).ReturnsAsync(User());var delivery=new Mock<IResetDelivery>();var audit=new Mock<IAuditRepository>();await new UserManagementService(ur.Object,audit.Object,delivery.Object).RequestResetAsync("u",Actor());delivery.Verify(x=>x.SendAsync(It.IsAny<StaffUser>()));audit.Verify(x=>x.AppendAsync(It.Is<AuditEvent>(e=>e.EventType=="PasswordResetRequested"&&e.Reason==null)));}
 [Fact]public async Task Media_delete_removes_storage_first(){var mr=new Mock<IMediaRepository>();mr.Setup(x=>x.FindAsync("m")).ReturnsAsync(Media());var storage=new Mock<IAssetStorage>();await new MediaManagementService(mr.Object,storage.Object,Mock.Of<IAuditRepository>()).DeleteAsync("m","policy",Actor());storage.Verify(x=>x.DeleteAsync("clip"));mr.Verify(x=>x.DeleteAsync("m"));}
 [Fact]public async Task Media_delete_requires_reason(){await Assert.ThrowsAsync<DashboardRuleException>(()=>new MediaManagementService(Mock.Of<IMediaRepository>(),Mock.Of<IAssetStorage>(),Mock.Of<IAuditRepository>()).DeleteAsync("m","",Actor()));}
 [Fact]public async Task Reporting_maps_all_totals(){var m=new Mock<IMediaRepository>();m.Setup(x=>x.CountsAsync()).ReturnsAsync(new Dictionary<string,long>{{"video",2},{"image",3},{ReviewStates.InReview,1}});var u=new Mock<IUserRepository>();u.Setup(x=>x.CountsAsync()).ReturnsAsync(new Dictionary<string,long>{{"Total",7},{"Verified",5}});var result=await new ReportingService(m.Object,u.Object).GetAsync();Assert.Equal(5,result.TotalMedia);Assert.Equal(7,result.TotalUsers);Assert.Equal(1,result.Pending);}
}
