import { useState, type FormEvent } from 'react';
import { ArrowRight, CheckCircle2 } from 'lucide-react';
import { api } from '../api';
import { useAuth } from '../context/AuthContext';

export default function AuthPage({ register = false }: { register?: boolean }) {
  const { signIn } = useAuth(); const [sent, setSent] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(''); const data = new FormData(event.currentTarget); try { if (register) { await api.register(String(data.get('name')), String(data.get('email')), String(data.get('password'))); setSent(true); } else { await signIn(String(data.get('email')), String(data.get('password'))); location.href = '/'; } } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } };
  if (sent) return <div className="center-card success"><CheckCircle2 /><h1>Check your inbox</h1><p>We sent you a verification link. Follow it to finish setting up your account.</p><a href="/signin" className="button primary">Continue to sign in</a></div>;
  return <div className="auth-wrap"><div className="auth-aside"><span className="eyebrow">Welcome to Aura</span><h1>{register ? 'Create. Share. Inspire.' : 'Welcome back.'}</h1><p>{register ? 'Join a community built around media that matters.' : 'Your next discovery is waiting.'}</p></div><form className="auth-form" onSubmit={submit}><span className="eyebrow">{register ? 'Get started' : 'Member access'}</span><h2>{register ? 'Create your account' : 'Sign in to Aura'}</h2>{error && <p className="inline-error">{error}</p>}{register && <label>Name<input name="name" required placeholder="Your name" /></label>}<label>Email address<input name="email" type="email" required placeholder="you@example.com" /></label><label>Password<input name="password" type="password" minLength={8} required placeholder="At least 8 characters" /></label>{!register && <a className="forgot-link" href="/forgot-password">Forgot your password?</a>}<button className="button primary" disabled={busy}>{busy ? 'Please wait…' : register ? 'Create account' : 'Sign in'}<ArrowRight size={17} /></button><p>{register ? 'Already a member?' : 'New to Aura?'} <a href={register ? '/signin' : '/register'}>{register ? 'Sign in' : 'Create an account'}</a></p></form></div>;
}
