import { useState, type FormEvent } from 'react';
import { UploadCloud, FileVideo, CheckCircle2, X } from 'lucide-react';
import { api } from '../api';

export default function UploadPage() {
  const [file, setFile] = useState<File | null>(null); const [done, setDone] = useState(false); const [description, setDescription] = useState(''); const [progress, setProgress] = useState(0); const [error, setError] = useState('');
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!file) return; setError(''); const data = new FormData(event.currentTarget); try { await api.upload(file, String(data.get('title')), description, String(data.get('tags')).split(',').map(tag => tag.trim()).filter(Boolean), setProgress); setDone(true); } catch (reason) { setError((reason as Error).message); } };
  if (done) return <div className="center-card success"><CheckCircle2 /><h1>Your media is under review.</h1><p>We’ll make it available as soon as the review is complete. Follow its status from My Uploads.</p><a className="button primary" href="/my-uploads">View my uploads</a></div>;
  return <div className="page-narrow"><div className="page-heading"><span className="eyebrow">Creator studio</span><h1>Share something remarkable.</h1><p>Video, image, or audio — bring your work to Aura.</p></div><form className="upload-form" onSubmit={submit}><label className="dropzone"><input type="file" accept="video/*,image/*,audio/*" onChange={event => setFile(event.target.files?.[0] ?? null)} required />{file ? <><FileVideo /><strong>{file.name}</strong><span>{(file.size / 1048576).toFixed(1)} MB</span></> : <><UploadCloud /><strong>Drop your media here</strong><span>or click to browse · Large files upload in resilient parts</span></>}</label>{file && <button type="button" className="remove-file" onClick={() => setFile(null)}><X />Remove</button>}<div className="form-grid"><label>Title <span>Optional</span><input name="title" placeholder="Untitled masterpiece" /></label><label className="full">Description <span>{description.length}/255</span><textarea name="description" maxLength={255} value={description} onChange={event => setDescription(event.target.value)} placeholder="Tell people about this media…" /></label><label className="full">Tags <span>Separate with commas</span><input name="tags" placeholder="travel, ambient, documentary" /></label></div><div className="responsibility"><strong>You are responsible for the media you upload.</strong><span>Only share work you own or have permission to use.</span></div>{error && <p className="inline-error">{error}</p>}{progress > 0 && progress < 100 && <div className="progress" aria-label={`Upload ${progress}% complete`}><span style={{ width: `${progress}%` }} /></div>}<button className="button primary submit-upload" disabled={!file || (progress > 0 && progress < 100)}>Upload for review <UploadCloud /></button></form></div>;
}
